name: Compile .tex Notes

on:
  push:
    paths:
      - "**.tex"
  pull_request:
    paths:
      - "**.tex"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Compile LaTeX files
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            **/*.tex
          work_in_root_file_dir: true

      - name: Move PDFs to compiled directory
        run: |
          mkdir -p compiled
          find . -name '*.pdf' | while read pdf; do
            base=$(basename "$pdf")
            mv "$pdf" "compiled/$base"
          done

      - name: Commit and push PDFs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f compiled/*.pdf
          if ! git diff --cached --quiet; then
            git commit -m "Update compiled PDFs [skip ci]"
            git push
          else
            echo "No PDF changes to commit"
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: compiled-$(date +'%Y%m%d-%H%M%S')
          name: "Compiled PDFs - $(date +'%Y-%m-%d %H:%M:%S')"
          files: compiled/*.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
